version: "3"

#ideas taken from https://knplabs.com/en/blog/how-to-dockerise-a-symfony-4-project

services:
  symfony_app:
    build:
      context: symfony_app
      dockerfile: Dockerfile
    container_name: basicrum_bo_php
    volumes:
      - ./../:/usr/src/app
      - ./symfony_app/.env:/usr/src/app/.env
    depends_on:
      - db
    links:
      - db
    networks:
      - basicrum_bo_network

  db:
    image: mysql:8.0.15
    container_name: basicrum_bo_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: basicrum_demo
      MYSQL_USER: roottest
      MYSQL_PASSWORD: roottest
    volumes:
      - ./db/data/basicrum_demo_2019-04-28.sql.gz:/docker-entrypoint-initdb.d/basicrum_demo_2019-04-28.sql.gz
    networks:
      - basicrum_bo_network
    ports:
      - 3308:3306

  nginx:
    image: nginx:1.15.11-alpine
    container_name: basicrum_bo_nginx
    volumes:
      - ./../public/:/usr/src/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8086:80
    depends_on:
      - symfony_app
    networks:
      - basicrum_bo_network

networks:
  basicrum_bo_network:
    driver: bridge

