version: "2.1"

#ideas taken from https://knplabs.com/en/blog/how-to-dockerise-a-symfony-4-project

services:
  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: basicrum_demo
      MYSQL_USER: basicrum_demo
      MYSQL_PASSWORD: basicrum_demo
    networks:
      basicrum_bo_network:
        aliases:
          - db
    ports:
    - 3308:3306

  nginx:
    image: nginx:1.16.0-alpine
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8086:80
    depends_on:
    - db
    - fpm
    networks:
    - basicrum_bo_network
  
  fpm:
    build:
      context: symfony_app
      dockerfile: Dockerfile
    env_file: ./symfony_app/.env
    volumes:
      - ./../:/usr/src/app
    networks:
      basicrum_bo_network:
        aliases:
          - fpm

networks:
  basicrum_bo_network:
    driver: bridge